### ISSUE TITLE
Getting Array out of bound exeption

### ISSUE THREAD

**Issue by MinkiPan-zz** [cookpad/license-tools-plugin#55]
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
        at com.cookpad.android.licensetools.ArtifactId.parse(ArtifactId.java:27)
        at com.cookpad.android.licensetools.LicenseToolsPlugin$_loadDependencyLicenses_closure5.doCall(LicenseToolsPlugin.groovy:121)
        at com.cookpad.android.licensetools.LicenseToolsPlugin.loadDependencyLicenses(LicenseToolsPlugin.groovy:110)
        at com.cookpad.android.licensetools.LicenseToolsPlugin$loadDependencyLicenses$0.callCurrent(Unknown Source)
        at com.cookpad.android.licensetools.LicenseToolsPlugin.initialize(LicenseToolsPlugin.groovy:94)
        at com.cookpad.android.licensetools.LicenseToolsPlugin$_apply_closure1.doCall(LicenseToolsPlugin.groovy:26)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:637)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
        ... 73 more

command was ./gradlew checkLicenses --stacktrace
can someone help me, i am not getting any smarter by reading the trace

**Comment by uzzu** [comment]
Hmm... Could you paste your licenses.yml into a comments or gist?

**Comment by MinkiPan-zz** [comment]
wait, as far as I understand checkLicenses will generate the yml file right, or do I have to define ot manually? I don't have a license.yml file defined

**Comment by litmon** [comment]
`checkLicenses` does not generate `licenses.yml` automatically, so you should make `licenses.yml` file and put `app/licenses.yml` or some location you defined in `build.gradle`.
https://github.com/cookpad/license-tools-plugin#configuring-the-plugin

**Comment by MinkiPan-zz** [comment]
`- artifact: com.android.support:+:+
  name: Android Support Libraries
  copyrightHolder: The Android Open Source Project
  license: apache2
`

okay I created this example .yml file, but keep getting the error

**Comment by burakozhan** [comment]
Same here, getting ArrayIndexOutOfBounds, no matter if I have the yml file or not. 

`Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
        at com.cookpad.android.licensetools.ArtifactId.parse(ArtifactId.java:24)
        at com.cookpad.android.licensetools.LicenseToolsPlugin$_loadDependencyLicenses_closure5.doCall(LicenseToolsPlugin.groovy:121)
        at com.cookpad.android.licensetools.LicenseToolsPlugin.loadDependencyLicenses(LicenseToolsPlugin.groovy:110)
        at com.cookpad.android.licensetools.LicenseToolsPlugin$loadDependencyLicenses$0.callCurrent(Unknown Source)
        at com.cookpad.android.licensetools.LicenseToolsPlugin.initialize(LicenseToolsPlugin.groovy:94)
        at com.cookpad.android.licensetools.LicenseToolsPlugin$_apply_closure1.doCall(LicenseToolsPlugin.groovy:26)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:681)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
`

**Comment by juyaki** [comment]
Same problem here.. Did anyone find a solution ?

**Comment by k4zy** [comment]
We are going to archive this repository.  
Please migrate https://github.com/kazyApp/LicenseToolsPlugin  
We already resolved this problem. (If you have been get this problem, create Issue 
 and sample yaml)
Thanks.
